image: ubuntu:24.04

stages:
  - test

test:
  stage: test
  tags:
    - wireguard

  before_script:
    - apt update
    - apt install -y openssh-client
    - mkdir -p ~/.ssh
    - ssh-keyscan 10.10.0.5 >> ~/.ssh/known_hosts

  script:
    - ssh oskar@10.10.0.5 hostname