stages:
  - test

test-wireguard:
  stage: test
  script:
    - echo "Runner:"
    - hostname
    - echo "Verbindung zu Ubuntu testen:"
    - ssh oskar@10.10.0.5 "hostname"
    - ssh oskar@10.10.0.5 "uptime"